# Generated by Django 3.1 on 2021-01-25 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0003_productimage'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productimage',
            options={},
        ),
        migrations.AlterField(
            model_name='productimage',
            name='file',
            field=models.ImageField(upload_to='static/'),
        ),
    ]
